package GUI;


import Exceptions.KeyringException;
import Keyring.Keyring;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

public class Autenticate extends javax.swing.JFrame {
    
    public Autenticate() {
        initComponents();
        javax.swing.JFrame me = this;
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER,0),"clickButton");
        this.getRootPane().getActionMap().put("clickButton",new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton_autenticate.doClick();                
            }
        });
        
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                System.out.println("\n<----- KEYRING ----->");
            }
        });
        
        try {
            Keyring.checkFile();
        } catch (KeyringException ex) {
            JOptionPane.showMessageDialog(me, ex.getMessage(),ex.getTitleMsg(),ex.getTypeMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_autenticate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField_MasterKey = new javax.swing.JPasswordField();
        jButton_credits = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_version = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox_showPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keyring");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo1.png")));
        setResizable(false);

        jButton_autenticate.setText("Log in");
        jButton_autenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_autenticateActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter the master key");

        jButton_credits.setText("?");
        jButton_credits.setFocusable(false);
        jButton_credits.setRequestFocusEnabled(false);
        jButton_credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_creditsActionPerformed(evt);
            }
        });

        jLabel9.setText("By " + Keyring.author);

        jLabel_version.setText("v. "+Keyring.version);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jCheckBox_showPass.setText("Show password\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_version))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jCheckBox_showPass))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_credits))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordField_MasterKey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_autenticate)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_credits)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_autenticate)
                    .addComponent(jPasswordField_MasterKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox_showPass))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_version)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        char defaultEchoChar = jPasswordField_MasterKey.getEchoChar();

        jCheckBox_showPass.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    jPasswordField_MasterKey.setEchoChar((char) 0);
                } else {
                    jPasswordField_MasterKey.setEchoChar(defaultEchoChar);
                }
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_autenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_autenticateActionPerformed
        try {
            String masterKey = String.valueOf(jPasswordField_MasterKey.getPassword());
            
            KeyringMain k = new KeyringMain(new Keyring(masterKey));
            k.setLocationRelativeTo(this);
            k.setVisible(true);
            this.dispose();
        } catch (KeyringException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),ex.getTitleMsg(),ex.getTypeMessage());
        }
    }//GEN-LAST:event_jButton_autenticateActionPerformed

    private void jButton_creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_creditsActionPerformed
        Credits c = new Credits(this, true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
    }//GEN-LAST:event_jButton_creditsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_autenticate;
    private javax.swing.JButton jButton_credits;
    private javax.swing.JCheckBox jCheckBox_showPass;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_version;
    private javax.swing.JPasswordField jPasswordField_MasterKey;
    // End of variables declaration//GEN-END:variables
}
