package GUI;

import Exceptions.KeyringException;
import Keyring.Keyring;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nino
 */
public class EditMasterKey extends javax.swing.JDialog {

    /**
     * Creates new form EditMasterKEy
     * @param parent
     * @param modal
     * @param keyring
     */
    public EditMasterKey(java.awt.Frame parent, boolean modal, Keyring keyring) {
        super(parent, modal);
        initComponents();
        this.keyring = keyring;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField_MasterKey = new javax.swing.JPasswordField();
        jButton_confirm = new javax.swing.JButton();
        jButton_credits = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_showPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit master key");
        setPreferredSize(new java.awt.Dimension(332, 165));

        jButton_confirm.setText("Confirm");
        jButton_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmActionPerformed(evt);
            }
        });

        jButton_credits.setText("?");
        jButton_credits.setFocusable(false);
        jButton_credits.setRequestFocusEnabled(false);
        jButton_credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_creditsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Enter the new master key");

        jCheckBox_showPass.setText("Show password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_credits))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPasswordField_MasterKey, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_confirm))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox_showPass)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_credits)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_confirm)
                    .addComponent(jPasswordField_MasterKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_showPass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        char defaultEchoChar = jPasswordField_MasterKey.getEchoChar();

        jCheckBox_showPass.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    jPasswordField_MasterKey.setEchoChar((char) 0);
                } else {
                    jPasswordField_MasterKey.setEchoChar(defaultEchoChar);
                }
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmActionPerformed
        try {
            String masterKey = String.valueOf(jPasswordField_MasterKey.getPassword());
            keyring.setMasterKey(masterKey);
            keyring.save();
            JOptionPane.showMessageDialog(this,"You have successfully updated the master key.", "Master key update", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (KeyringException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),ex.getTitleMsg(),ex.getTypeMessage());
        }
    }//GEN-LAST:event_jButton_confirmActionPerformed

    private void jButton_creditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_creditsActionPerformed
        Credits c = new Credits((Frame) this.getParent(), true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
    }//GEN-LAST:event_jButton_creditsActionPerformed

    private final Keyring keyring;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_confirm;
    private javax.swing.JButton jButton_credits;
    private javax.swing.JCheckBox jCheckBox_showPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField_MasterKey;
    // End of variables declaration//GEN-END:variables
}
